### ISSUE TITLE
Check if install will trigger select

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium#590]
User reported seeing `[INFO]   tiapp.xml <sdk-version> set to 11.0.0.GA, but current Titanium SDK set to 10.1.1.GA` with 11.0.0 installed. 
Need to check if `ti sdk install latest` (without `--default`) was selecting the SDK before.

If not:
* should `-d` be default? 
* should we ask at the end to select it 
* should we show a `run ti select` message

**Comment by cb1kenobi** [comment]
I seriously contemplated making `-d` the default, but that's a major change and we just shipped CLI v6, so I didn't want to ship v7 so soon.

When I was working on Titanium CLI.next last year, I completely got rid of the `ti select` command, which I think is the correct answer here. The only reason `ti select` exists is because I was worried if I put the `tiapp.xml` parser in the CLI, then we could add something down the road in the SDK that the CLI's `tiapp.xml` parser couldn't understand. Nowadays, the `tiapp.xml` doesn't change much, so we can put the `tiapp.xml` parser in the CLI and thus get rid of `ti select`.

As far as parser implementation, the one the SDK uses is here: https://github.com/tidev/node-titanium-sdk/blob/master/lib/tiappxml.js. This wires up every known tag to a JSON object property. It's very possible for older versions of the SDK to not know how to parse newer tags in the `tiapp.xml`.

Alloy took a different approach where it only knows how to parse very specific tags: https://github.com/tidev/alloy/blob/master/Alloy/tiapp.js.

Titanium CLI.next had a really cool `tiapp.xml` parser where used JS proxies and mapped properties to XML nodes live. It was maybe 75% finished. Very simple definition. Simple validation. Very, very complex implementation under the hood. https://github.com/tidev/titaniumlib/blob/312e805ad3c3c21b0f8e20a55ba479ee219e72ab/src/project/tiapp.js.

So my vote is for the CLI to use node-titanium-sdk's `tiapp.xml` parser, then get rid of `ti select`. I don't think it would be a breaking change as we'd just be moving the `tiapp.xml` parsing from the SDK into the CLI and it would just select the correct SDK for the project.

As for new projects, we don't have to define a `<sdk-version>`, so we can simply create a new project using one of the templates from https://github.com/tidev/titanium-templates/tree/master/packages.

By making these changes, we can remove a bunch of code from the CLI and the SDK as well as the project templates from the SDK. It's a win-win.

**Comment by m1ga** [comment]
Thanks for the insights :+1: 
So if I get it right: if I have an old SDK with `ti select` it could make a difference if I compile an app with a newer `sdk-version` if new fields are introduced in tiapp.xml because it will use the old SDK parser.

> So my vote is for the CLI to use node-titanium-sdk's tiapp.xml parser, then get rid of ti select.

Sounds good to me! 

> By making these changes, we can remove a bunch of code from the CLI and the SDK as well as the project templates from the SDK. It's a win-win.

:+1: :+1: :+1: :+1: 

I think for a "short term" solution we could just show a message after `ti install` to use `ti select` for now. Won't harm since most people use it and it could be done in a minor update. That way people know how to get rid of the warning. New users who do a SDK update the first time don't know all of this
